import {AppTheme} from './theme';

export const lightTheme: AppTheme = {
  colors: {
    primary: '#7C3AED',
    primaryDark: '#5B21B6',
    primaryLight: '#F5F3FF',
    secondary: '#8B5CF6',
    secondaryLight: '#EDE9FE',
    background: '#F8FAFC',
    surface: '#FFFFFF',
    textPrimary: '#0F172A',
    textSecondary: '#64748B',
    textTertiary: '#94A3B8',
    textDisabled: '#CBD5E1',
    border: '#E2E8F0',
    borderLight: '#F1F5F9',
    danger: '#EF4444',
    dangerLight: '#FEF2F2',
    warning: '#F59E0B',
    warningLight: '#FFFBEB',
    info: '#3B82F6',
    infoLight: '#EFF6FF',
    success: '#10B981',
    successLight: '#ECFDF5',
    white: '#FFFFFF',
    black: '#000000',
    overlay: 'rgba(0, 0, 0, 0.5)',
    statusNew: '#3B82F6',
    statusPending: '#F59E0B',
    statusUnderReview: '#8B5CF6',
    statusDone: '#10B981',
    headerBackground: '#7C3AED',
    headerText: '#FFFFFF',
    fabBackground: '#7C3AED',
    chipText: '#FFFFFF',
    statusNewLight: '#EFF6FF',
    statusPendingLight: '#FFFBEB',
    statusUnderReviewLight: '#F5F3FF',
    statusDoneLight: '#ECFDF5',
    skeleton: '#E2E8F0',
    skeletonHighlight: '#F1F5F9',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    xxxl: 32,
  },
  typography: {
    heading: {fontSize: 20, fontWeight: '700'},
    subheading: {fontSize: 16, fontWeight: '600'},
    body: {fontSize: 14, fontWeight: '400'},
    bodySmall: {fontSize: 12, fontWeight: '400'},
    label: {fontSize: 12, fontWeight: '500'},
    caption: {fontSize: 11, fontWeight: '400'},
  },
  borderRadius: {
    sm: 6,
    md: 10,
    lg: 12,
    xl: 16,
  },
  shadows: {
    sm: {
      shadowColor: '#000000',
      shadowOffset: {width: 0, height: 1},
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    md: {
      shadowColor: '#000000',
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.08,
      shadowRadius: 4,
      elevation: 2,
    },
    lg: {
      shadowColor: '#000000',
      shadowOffset: {width: 0, height: 4},
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 4,
    },
  },
};
